### PR TITLE
Update README with official chromedriver bin link

### PR DESCRIPTION
**Pull request by apparition47**
Great fork but the current linked chromedriver binary doesn't work for me and the binaries off that site aren't updated anymore. The newest compiled versions off the official Chromium project site work great.

Just a minor suggestion 👍

### CODE REVIEW

**Comment by eduramiba** [comment]
Problem is this patched appium still won't work with an standard chromedriver. I actually uploaded a patched chromedriver that accepts the `androidDeviceSocket` chromeOption. You can make it work with crosswalk by using the appium capability `androidDeviceSocket` (same name, yes, and you actually won't need this patched appium at all).

So you can make it work with unmodified appium 1.5.3 and the patched chromedriver. This way, appium will detect a `CHROMIUM` webview context, and you will be able to set that context. I will update the readme in this repository with the example code.

**Comment by eduramiba** [comment]
Oh, the chromedriver binary for linux is here https://github.com/eduramiba/appium/releases/tag/1.5.3

**Comment by apparition47** [comment]
Thanks for the tip. Does this method with the patched chromedriver work with the `autoWebView: true` capability?

**Comment by eduramiba** [comment]
No it does not work with autoWebview, please check the updated readme: https://github.com/eduramiba/appium/blob/master/README.md

**Comment by apparition47** [comment]
Thanks!

**Pull request closed without merging**
